source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '9.0'

target 'SchibstedAccount_Example' do
  pod 'SchibstedAccount', :path => '../'
  pod 'SchibstedAccount/UI', :path => '../'

  target 'SchibstedAccount_Tests' do
    inherit! :search_paths

    pod 'Quick', '= 1.2.0'
    pod 'Nimble', '= 7.0.3', :inhibit_warnings => true #Needed because of deprecated warnings. See: https://github.com/Quick/Nimble/issues/444
    if !ENV['TRAVIS']
      pod 'SwiftFormat/CLI', '= 0.32.0'
    end
  end
end

post_install do |installer|
  installer.pods_project.root_object.attributes["ORGANIZATIONNAME"] = "Schibsted Products & Technology"

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == 'SchibstedAccount'
        config.build_settings['SWIFT_TREAT_WARNINGS_AS_ERRORS'] = 'YES'
        if config.name == 'Debug'
          config.build_settings['OTHER_SWIFT_FLAGS'] = '-DDEBUG'
        else
          config.build_settings['OTHER_SWIFT_FLAGS'] = ''
        end
      end
    end
  end
end

ENV['COCOAPODS_DISABLE_STATS'] = 'true'
